import fs   from 'fs/promises';
import path from 'path';

export async function saveBlogHTML(blog, date, edition, config) {
  await fs.mkdir(config.blogOutputDir, { recursive: true });
  const filename  = date + '-' + edition + '.html';
  const filePath  = path.join(config.blogOutputDir, filename);
  const publicUrl = config.siteUrl + '/blog/' + filename;
  await fs.writeFile(filePath, buildArticlePage(blog, publicUrl, config), 'utf8');
  await updateManifest(blog, date, edition, filename, publicUrl, config);
  return [filePath];
}

function buildArticlePage(blog, canonicalUrl, config) {
  const faqHtml  = blog.faqs.map(f => '<div class="faq-item"><h3 class="faq-q">' + esc(f.q) + '</h3><p class="faq-a">' + esc(f.a) + '</p></div>').join('');
  const tagsHtml = blog.seoTags.map(t => '<a href="' + config.siteUrl + '/tag/' + slugify(t) + '" class="seo-tag">' + esc(t) + '</a>').join('');

  return '<!DOCTYPE html>\n<html lang="en">\n<head>\n' +
    '<meta charset="UTF-8">\n' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">\n' +
    '<title>' + esc(blog.seoTitle) + ' | ' + config.siteName + '</title>\n' +
    '<meta name="description" content="' + esc(blog.metaDesc) + '">\n' +
    '<meta name="keywords" content="' + esc(blog.seoTags.join(', ')) + '">\n' +
    '<link rel="canonical" href="' + canonicalUrl + '">\n' +
    '<style>\n' +
    '*{box-sizing:border-box;margin:0;padding:0}\n' +
    'body{font-family:-apple-system,sans-serif;color:#1a1a1a;background:#fff;line-height:1.75}\n' +
    '.site-header{background:#1a3a5c;padding:14px 24px}\n' +
    '.site-header a{color:#fff;text-decoration:none;font-weight:700;font-size:20px}\n' +
    'article{max-width:780px;margin:0 auto;padding:24px 20px 60px}\n' +
    'h1{font-size:28px;font-weight:700;line-height:1.35;margin-bottom:12px;color:#1a3a5c}\n' +
    'h2{font-size:20px;font-weight:600;margin:32px 0 10px;color:#1a3a5c;border-bottom:2px solid #e8f0f8;padding-bottom:6px}\n' +
    'h3{font-size:17px;font-weight:600;margin:20px 0 8px;color:#2c4a6e}\n' +
    'p{margin-bottom:14px}\n' +
    'ul,ol{margin:8px 0 14px 20px}\n' +
    'li{margin-bottom:5px}\n' +
    '.faq-section{background:#f0f4f9;border-radius:10px;padding:24px;margin:36px 0 24px}\n' +
    '.faq-item{margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid #dce4ef}\n' +
    '.faq-item:last-child{border:none}\n' +
    '.faq-q{font-size:15px;font-weight:600;margin-bottom:6px;color:#1a3a5c}\n' +
    '.faq-a{font-size:14px;color:#444}\n' +
    '.seo-tag{display:inline-block;background:#e8f0f8;color:#185fa5;font-size:12px;padding:3px 10px;border-radius:20px;margin:3px;text-decoration:none}\n' +
    '.disclaimer{background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:14px 16px;margin-top:32px;font-size:13px;color:#7f1d1d}\n' +
    'footer{background:#1a3a5c;color:#9ab3cb;text-align:center;padding:24px;font-size:13px;margin-top:60px}\n' +
    'footer a{color:#7eb4d8;text-decoration:none}\n' +
    '</style>\n</head>\n<body>\n' +
    '<header class="site-header"><a href="' + config.siteUrl + '">' + config.siteName + '</a></header>\n' +
    '<article>\n' +
    '<h1>' + esc(blog.seoTitle) + '</h1>\n' +
    blog.htmlContent + '\n' +
    '<section class="faq-section"><h2>Frequently Asked Questions</h2>' + faqHtml + '</section>\n' +
    '<div style="margin-top:28px"><p style="font-size:14px;color:#666;margin-bottom:8px">Topics covered:</p>' + tagsHtml + '</div>\n' +
    '<div class="disclaimer"><strong>Disclaimer:</strong> This article is for informational purposes only. Market investments are subject to risk. Consult a SEBI-registered financial advisor before investing.</div>\n' +
    '</article>\n' +
    '<footer><p>2026 ' + config.siteName + ' | Auto-generated by Gemini AI (Free)</p></footer>\n' +
    '</body>\n</html>';
}

async function updateManifest(blog, date, edition, filename, publicUrl, config) {
  let manifest = { articles: [] };
  try {
    const raw = await fs.readFile(config.manifestPath, 'utf8');
    manifest  = JSON.parse(raw);
  } catch { }

  manifest.articles = manifest.articles.filter(a => !(a.date === date && a.edition === edition));
  manifest.articles.unshift({
    date, edition, filename, url: publicUrl,
    title: blog.seoTitle, metaDesc: blog.metaDesc,
    seoTags: blog.seoTags.slice(0, 6),
    wordCount: blog.wordCount, generatedAt: blog.generatedAt,
  });
  manifest.articles  = manifest.articles.slice(0, 90);
  manifest.updatedAt = new Date().toISOString();
  await fs.writeFile(config.manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
}

const esc     = s => String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const slugify = s => s.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');
